#![forbid(unsafe_code)]

use render_events::Events;
use std::{any::Any, error::Error};
pub mod absolute;
mod types;
pub use types::*;
mod general;
pub use general::*;

type Area = (u32, u32, u32, u32);

pub trait Layoutable {
    fn children(&self) -> Vec<Layouted<dyn InternalLayoutable>> {
        vec![]
    }
}

pub trait InternalLayoutable: Layoutable + Any {
    fn get_width(&self) -> u32;
    fn set_width(&mut self, width: u32);
    fn get_height(&self) -> u32;
    fn set_height(&mut self, height: u32);
    fn get_x(&self) -> u32;
    fn set_x(&mut self, x: u32);
    fn get_y(&self) -> u32;
    fn set_y(&mut self, y: u32);
    fn get_children_mut(&mut self) -> &mut Vec<Layouted<dyn InternalLayoutable>>;
    fn new() -> Self
    where
        Self: Sized;
    fn serialize(&self) -> String {
        format!(
            "{}(x:{}, y:{}, width:{}, height:{})",
            std::any::type_name::<Self>(),
            self.get_x(),
            self.get_y(),
            self.get_width(),
            self.get_height()
        )
    }
    // WARNING: AI GENERATED
    /// Upcast this node to a `&dyn Layoutable` reference.
    ///
    /// This is needed because trait default methods have `Self: ?Sized`,
    /// which prevents direct coercion from `&Self` to `&dyn Layoutable`.
    /// Concrete types generated by `#[layoutable]` implement this by
    /// returning `self`, which works because concrete types are `Sized`.
    fn as_layoutable(&mut self) -> &mut dyn InternalLayoutable;

    fn into_any(self: Box<Self>) -> Box<dyn Any>;

    fn as_any(&self) -> &dyn Any;

    fn layout(&mut self, scale: f64) -> Result<Vec<Box<dyn Primitive>>, Box<dyn Error>> {
        let area = (
            self.get_x(),
            self.get_y(),
            self.get_width(),
            self.get_height(),
        );
        general_layout(
            self,
            area,
            &absolute::absolute_layout, // change this
            scale,
        )
    }

    fn into_primitive(&self) -> Option<Box<dyn Primitive>> {
        None
    }
}

pub trait Primitive: InternalLayoutable {
    fn get_children_mut(&mut self) -> &mut Vec<Box<dyn InternalLayoutable>> {
        panic!("Primitives do not have children.");
    }
}

impl std::fmt::Debug for dyn Primitive {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.serialize())
    }
}

pub trait EventHandler: InternalLayoutable {
    fn handle_event(&mut self, event: Events) {
        match event {
            Events::Resize { width, height } => self.handle_resize(width, height),
            Events::Move { x, y } => self.handle_move(x, y),
            Events::Hover { x, y } => {
                self.handle_hover(x, y);
            }
            _ => {
                todo!(
                    "Handle other events in RenderComponent. Got event: {:?}",
                    event
                )
            }
        }
    }

    fn handle_resize(&mut self, width: u32, height: u32) {
        self.set_width(width);
        self.set_height(height);
    }
    fn handle_move(&mut self, x: u32, y: u32) {
        self.set_x(x);
        self.set_y(y);
    }

    fn handle_hover(&mut self, _x: u32, _y: u32) {
        // By default, do nothing
    }
}

impl EventHandler for dyn InternalLayoutable {}
