use std::any::Any;

use render_events::Events;

use crate::layouting::ConvertedPrimitive;

pub mod layouting;
pub mod positioning;
pub mod sizing;

pub struct Layout<'a> {
    pub sizing: sizing::Sizing<'a>,
    pub positioning: positioning::Positioning,
}

pub trait Layoutable {
    fn get_sizing(&'_ self) -> sizing::Sizing<'_>;
    fn get_position(&self) -> positioning::Positioning {
        positioning::Positioning::default()
    }
    fn children(&self) -> Vec<Box<dyn InternalLayoutable>> {
        vec![]
    }
}

pub trait InternalLayoutable: Layoutable + Any {
    fn get_width(&self) -> u32;
    fn set_width(&mut self, width: u32);
    fn get_height(&self) -> u32;
    fn set_height(&mut self, height: u32);
    fn get_x(&self) -> u32;
    fn set_x(&mut self, x: u32);
    fn get_y(&self) -> u32;
    fn set_y(&mut self, y: u32);
    fn get_children_mut(&mut self) -> &mut Vec<Box<dyn InternalLayoutable>>;
    fn new() -> Self
    where
        Self: Sized;
    fn serialize(&self) -> String {
        format!(
            "{}(x:{}, y:{}, width:{}, height:{})",
            std::any::type_name::<Self>(),
            self.get_x(),
            self.get_y(),
            self.get_width(),
            self.get_height()
        )
    }
    // WARNING: AI GENERATED
    /// Upcast this node to a `&dyn Layoutable` reference.
    ///
    /// This is needed because trait default methods have `Self: ?Sized`,
    /// which prevents direct coercion from `&Self` to `&dyn Layoutable`.
    /// Concrete types generated by `#[layoutable]` implement this by
    /// returning `self`, which works because concrete types are `Sized`.
    fn as_layoutable(&mut self) -> &mut dyn InternalLayoutable;

    fn into_any(self: Box<Self>) -> Box<dyn Any>;

    fn as_any(&self) -> &dyn Any;

    fn layout(
        &mut self,
        try_convert: &dyn Fn(&dyn Any) -> ConvertedPrimitive,
    ) -> Vec<Box<dyn Primitive>> {
        layouting::layout(
            self,
            self.get_x(),
            self.get_y(),
            self.get_width(),
            self.get_height(),
            try_convert,
        )
    }
}

pub trait Primitive: InternalLayoutable {
    fn get_children_mut(&mut self) -> &mut Vec<Box<dyn InternalLayoutable>> {
        panic!("Primitives do not have children.");
    }
}

impl std::fmt::Debug for dyn Primitive {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.serialize())
    }
}

pub trait EventHandler: InternalLayoutable {
    fn handle_event(&mut self, event: Events) {
        match event {
            Events::Resize { width, height } => self.handle_resize(width, height),
            Events::Move { x, y } => self.handle_move(x, y),
            Events::Hover { x, y } => {
                self.handle_hover(x, y);
            }
            _ => {
                todo!(
                    "Handle other events in RenderComponent. Got event: {:?}",
                    event
                )
            }
        }
    }

    fn handle_resize(&mut self, width: u32, height: u32) {
        self.set_width(width);
        self.set_height(height);
    }
    fn handle_move(&mut self, x: u32, y: u32) {
        self.set_x(x);
        self.set_y(y);
    }

    fn handle_hover(&mut self, _x: u32, _y: u32) {
        // By default, do nothing
    }
}

impl EventHandler for dyn InternalLayoutable {}
